### ISSUE TITLE
Wrong handling of empty msgstr

### ISSUE THREAD

**Issue by pontaoski** [mini2Dx/gettext#9]
An empty msgstr is treated as if the key exists and has a value of an empty string, rather than being treated as if the key doesn't exist, as specified by gettext.

Expectation:
```po
msgid "Orwell"
msgstr ""
```
```java
GetText.tr("Orwell") == "Orwell"
```

Reality:
```java
GetText.tr("Orwell") == ""
```

**Comment by tomcashman** [comment]
I'll have some time this evening to investigate and patch
